### ISSUE TITLE
Is there any information about the build environment

### ISSUE THREAD

**Issue by Tommo-L** [neow3j/neow3j#109]
Is there any information about the build environment like gradle, jdk version.
The developers of Okex exchange want to build the source code, but get an empty jar. And we have a try in our local, we have the same problem.

**Comment by gsmachado** [comment]
Hello @Tommo-L 

Sure, you can take a look at the Travis file: https://github.com/neow3j/neow3j/blob/master-2.x/.travis.yml and get to know how to build neow3j. You need to use the `master-2.x` branch, since the Neo3 branches are under heavy development.

However, what's the use case? Is there anything OkEx wants to see or modify? We would like to know, really, to avoid forks and a fragmented community. What about if you put them in direct contact with us?

**Comment by Tommo-L** [comment]
Thanks. OkEx want to build the source code for security. They use neo3wj  for developing a auto-claim GAS tool.
