### ISSUE TITLE
No verbose=1 option for RPC getrawtransaction 

### ISSUE THREAD

**Issue by cloud8little** [neow3j/neow3j#15]
NeoGetRawTransaction getRawTransaction = neow3j.getRawTransaction("a7556ae2ef6acbf249a5f41e2e19859676f4717b47bf539954440e4a6eb975fe").send();
System.out.println(getRawTransaction.getResult().toCharArray());
System.out.println(getRawTransaction.getJsonrpc());

**Comment by gsmachado** [comment]
The JSON-RPC `getrawtransaction` method can be accessed through two different `neow3j` methods:

- `.getRawTransaction(String txHashId)`: which fetches the whole raw transaction in hex (i.e., verbose=0)
- `.getTransaction(String txHashId)`: which fetches the transaction in an object format, serialized (i.e., verbose=1)

We decided to have this distinction on the method name in order to help developers to distinguish without method parameters, which can be cryptic sometimes. It's a design decision.

Documentation can be found [here](https://github.com/neow3j/neow3j-examples/blob/613a0451a7759eadb9a2308aa17e75efc01221ff/src/main/java/io/neow3j/examples/jsonrpc/GetTransaction.java) and [here](https://github.com/neow3j/neow3j-examples/blob/613a0451a7759eadb9a2308aa17e75efc01221ff/src/main/java/io/neow3j/examples/jsonrpc/GetTransaction.java).
