### ISSUE TITLE
Transaction and Multisig usage example

### ISSUE THREAD

**Issue by nimmortal** [neow3j/neow3j#18]
Please, could you provide more detailed examples of RawTransaction and MultiSig usage.  

Currently, I am trying to collect tokens from test contract (https://docs.neo.org/en-us/network/testnet.html), but unfortunately I do not understand how to build such transaction, there are no any information about how RawTransaction.createContractTransaction really works.

**Comment by gsmachado** [comment]
Hello @nimmortal!
Yes, it's currently possible to make a rawtransaction with multisig address.
More specifically, you can check the example [here](https://github.com/neow3j/neow3j-examples/blob/master/src/main/java/io/neow3j/examples/transactions/CreateRawTransactionMultiSig.java).
If you still can't make such multisig transaction, can you please post here your current code snippet?

**Comment by nimmortal** [comment]
My problem is that I am not understand RawTransaction semantics.

To make clear my use case - I am trying to collect assets from test contract.

```java
Neow3j neow3j = Neow3j.build(new HttpService("http://seed1.ngd.network:20332"));

ECKeyPair ecKeyPair = ECKeyPair.create(WIF.getPrivateKeyFromWIF("******"));

WalletFile.Account account = Wallet.createStandardAccount("1234567890", ecKeyPair);

String publicKeyRaw = "03c02a93134f98d9c78ec54b1b1f97fc64cd81360f53a293f41e4ad54aac3c5717";
BigInteger publicKey = Numeric.toBigInt(Numeric.hexStringToByteArray(publicKeyRaw));

String multiSigAddress = Keys.getMultiSigAddress(
        1,
        ecKeyPair.getPublicKey(),
        publicKey
);
```
Here 'multiSigAddress' is correct and expected.

```java
RawVerificationScript verificationScript = Keys.getVerificationScriptFromPublicKey(
        1,
        ecKeyPair.getPublicKey(),
        publicKey
);

RawTransaction rawTx = RawTransaction.createContractTransaction(
       null,
       null,
       Arrays.asList(
              new RawTransactionInput("0adb19b2723818886ae524620bbdeb1cda0b3121dffd24a1f3feaa6fa0d3b1fb", 0)
        ),
        Arrays.asList(
               new RawTransactionOutput(0, NEOAsset.HASH_ID, "100.0", multiSigAddress)
        )
);
```
Here for me it is not clear what is Transaction input and Transaction output.

Could you explain it to me?

**Comment by claudemiller** [comment]
Hello @nimmortal 

You correctly specified in the transaction outputs that you want to send 100 NEO to the multiSigAddress. The outputs of a transaction specify who should receive how many NEO. 
But in order that you can acutally send those NEO you have to provide a proof that you own those NEO. This is what is done in the transaction inputs. In the inputs you specify where the NEO that you want to send are coming from. In your example you correctly specified an input coming from the transaction (hash: `0adb19b27...`). That input into your transaction is actually the output of the other transaction. And because a transaction can have multiple outputs you also have to specify which output is the one that you want to spend. You specified the output at index 0.
```
RawTransaction rawTx = RawTransaction.createContractTransaction(
       null,
       null,
       Arrays.asList(
               new RawTransactionInput("0adb19b2723818886ae524620bbdeb1cda0b3121dffd24a1f3feaa6fa0d3b1fb", 0)
        ),
        Arrays.asList(
               new RawTransactionOutput(0, NEOAsset.HASH_ID, "100.0", multiSigAddress)
        )
);
```

So far so good. We can check out the input transaction at [neo-scan](https://neoscan-testnet.io/transaction/0ADB19B2723818886AE524620BBDEB1CDA0B3121DFFD24A1F3FEAA6FA0D3B1FB). The index 0 refers to the first output of that transaction which goes to address `AHJrv6y6L6k9PfJvY7vtX3XTAmEprsd3Xn`. I assume that you own the private key for that address. Otherwise you can't spend that transaction output in your new transaction. Additionally, the output at index 0 must not have been spent before. I.e. it needs to be an *Unspent Transaction Output (UTXO)*.

The only thing that is missing in the above code is another transaction output. Because the value coming from transaction `0adb19b27...` is 1000 NEO and the first output in your transaction only spends 100 NEO, the remaining 900 NEO must be send back to your address. So the complete transaction looks like this:
```
RawTransaction rawTx = RawTransaction.createContractTransaction(
       null,
       null,
       Arrays.asList(
              new RawTransactionInput("0adb19b2723818886ae524620bbdeb1cda0b3121dffd24a1f3feaa6fa0d3b1fb", 0)),
        Arrays.asList(
               new RawTransactionOutput(0, NEOAsset.HASH_ID, "100.0", multiSigAddress)
	       new RawTransactionOutput(1, NEOAsset.HASH_ID, "900.0", Keys.getAddress(ecKeyPair1.getPublicKey())))
);
```

Hope that helps. Otherwise keep asking
We are also working on an automated example in the [neow3j-examples](https://github.com/neow3j/neow3j-examples) repository. It will look for transaction outputs to a given address and use the output for spending it on a new transaction.

**Comment by nimmortal** [comment]
Hi, @claudemiller

Thank you for such detailed overview of how to use multisig. 
I successfully received tokens from MultiSig account. I assume that this case can be more explained in documentation.

Unfortunately, this kind of usage is quite complex, so I am excited to hear about upcoming examples.

**Comment by claudemiller** [comment]
Hey @nimmortal 

> Why we should provide previous transaction in input?

The concept of transaction inputs and outputs (UTXO) is common to many blockchains (e.g. Bitcoin). This [site](https://docs.neo.org/developerguide/en/articles/blockchain/utxo.html) in the Neo docs has some information about it. To make it more convenient for the developer the concept is usually abstracted in other blockchain libraries. Neow3j does not *YET* provide a convenience layer to obtain unspent transaction outputs automatically for you.

If you already have a vision of how an API that removes this complexity should look, please let us know. Like, what methods would you expect in your use cases?
This would help us tailor the library to real use case needs :)

**Comment by gsmachado** [comment]
neow3j [version 2.0.1](https://github.com/neow3j/neow3j/releases/tag/2.0.1) was released and now transactions are way easier to be performed. I'm closing this issue. Feel free to re-open in case of doubts.
