### ISSUE TITLE
Set the wallet name by their public key

### ISSUE THREAD

**Issue by gsmachado** [neow3j/neow3j#189]
The user Evixis in Discord #java gave the suggestion:

> it would be really awesome if WalletUtils.generateNewWalletFile() would name wallets by their public key and not "neow3j". Like web3j does, because it's easier to locate the wallet in that way.

Therefore:
- [x] leave the option to the user how the wallet name should be set
- [x] ~set the default name as the public key (encoded)~

**Comment by csmuller** [comment]
Because a wallet can have multiple accounts, it is unclear after which account the wallet should be named. Simply the first account added?
If we use an account to name the wallet I think we should use its address and not its public key.

In neow3j >= 3.0.0 the affected methods are `createWallet(...)` and `withAccounts(...)`. 
For neow3j < 3.0.0 I haven't looked into it.

**Comment by gsmachado** [comment]
@csmuller yeah, I remember discussing this with you once...
The problem is that the NEP standard sets a name for the wallet, and not for the accounts, right?

**Comment by csmuller** [comment]
Both, accounts and wallets, have a name. Only on the wallet it is called 'label' 🥴.
For the accounts it is clear. We set the account's address as its name. But for the wallet we don't have much choice. The only sensible thing in my opinion is setting the name to the first account's address and maybe prepend 'wallet'.

**Comment by StoparPrimoz** [comment]
When we create a wallet with a function createNewWalletFile() there is created an account with a wallet. That willet file could have first created wallet as default wallet, which would be the name of the file (timestamp + default wallet).

Otherwise there could be a .find(File walletsFolder, Sting walletAddress) function, that would return wallet file with that address in it.

**Comment by gsmachado** [comment]
So, "easy" action points IMHO:
- [ ] Give developers the option to set a custom wallet name
- [ ] Set a different default wallet name if none is given

**Comment by mialbu** [comment]
This has been resolved by PR #221. I'll close it.

**Comment by csmuller** [comment]
> So, "easy" action points IMHO:
> 
> * [x]  Give developers the option to set a custom wallet name
> * [x]  Set a different default wallet name if none is given

I don't know what you guys discussed on this issue. Just wanted to point out that the second point (different default name) was not included in #221.
