### ISSUE TITLE
Implement Oracle wrapper class

### ISSUE THREAD

**Issue by mialbu** [neow3j/neow3j#264]
Neo's native contracts was extended with an [Oracle](https://github.com/neo-project/neo/pull/1584) ([discussion](https://github.com/neo-project/neo/issues/1272)) contract. We should provide a wrapper class for this contract.

**Comment by csmuller** [comment]
Requires the OracleService of neo-modules to complete testing. Moving it to the next milestone.

**Comment by csmuller** [comment]
@mialbu, @gsmachado Does it even make sense to have this Oracle wrapper class? Performing Oracle Requests from outside of a contract doesn't make much sense because for invoking the callback method the Oracle contract gets the calling contract's script hash which is not present for requests from outside of contracts.

**Comment by mialbu** [comment]
> @mialbu, @gsmachado Does it even make sense to have this Oracle wrapper class? Performing Oracle Requests from outside of a contract doesn't make much sense because for invoking the callback method the Oracle contract gets the calling contract's script hash which is not present for requests from outside of contracts.

After discussing with @csmuller and @gsmachado, we agreed to not implement a wrapper class for the oracle contract in the SDK due to the above mentioned point by @csmuller.
