### ISSUE TITLE
wallet: get balances (NEO and GAS)

### ISSUE THREAD

**Issue by gsmachado** [neow3j/neow3j#27]
As a developer, I would like to have methods exposed in the `wallet` module (#25) where I could get balances for NEO and GAS assets -- for addresses already existing on the wallet.

The UTXOs should be calculated based on the addresses added to the wallet, and the local file-based database state.

**Comment by claudemiller** [comment]
Issue was resolved with pull-request #45.
The Account class has a `balance` variable which holds all balances of that account. The implementation hands the control over when to update the balances to the developer. This is because an update requires an RPC. With `updateAssetBalances()` and `updateTokenBalances()` the developer is able to update the balances when he sees fit.
