### ISSUE TITLE
getnep17balances not reporting nep17 contract generated with neow3j

### ISSUE THREAD

**Issue by djm34** [neow3j/neow3j#436]
Hello, 

It seems I have another issue to report, the problem is present in  both 3.6.1 and 3.7.0
When generating a nep17 smartcontract (assuming BongoCatToken implements one since I worked mostly with that template for my tests), the generated contract is not reported by the  rpc method "getnep17balances". 

I tried yesterday to generate a contract using the csharp compiler to make sure that the rpc method was working and the one generated by that compiler gets reported.

May-be something is missing in the BongoCatToken example to make it work (?)

Thanks for your help
djm34

**Comment by csmuller** [comment]
Hey @djm34,
The problem seems to be the `transfer` event. In the `BongoCatToken` contract that event is named `transfer` with lowercase `t`, but the NEP-17 standard defines it with uppercase `T`. When I changed the event name (via the `@DisplayName` annotation) to `Transfer` the balances showed up with the `getnep17balances` RPC method.

We will fix that in the examples repository. Thanks a lot for pointing it out.

**Comment by csmuller** [comment]
This was fixed in the examples.
