### ISSUE TITLE
NEP-5 Token Contract API

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#70]
As a developer I need a unified API for interacting with NEP-5 token contracts. It should allow to conveniently retrieve token information and make transfers.
Example usage:
```
NEP5 token = NEP5.fromContractScriptHash("ceab719b8baa2310f232ee0d277c061704541cfb");
token.getBalanceOf("AJzoeKrj7RHMwSrPQDPdv61ciVEYpmhkjk")
token.getTotalSupply() 
...
token.transfer(fromAccount, toAddress, amount);
```

**Comment by gsmachado** [comment]
So, just adding more details about this issue:

High-level description:
- Implement the functionality described on https://github.com/neow3j/neow3j/issues/70.

Detailed description:
- Implement a wrapper class, like the ones implemented [here](https://github.com/neow3j/neow3j/blob/master/wallet/src/main/java/io/neow3j/wallet/AssetTransfer.java) or [here](https://github.com/neow3j/neow3j/blob/master/contract/src/main/java/io/neow3j/contract/ContractInvocation.java).
- The wrapper class can be called "NEP5", where it needs to expose the same methods as described in the [NEP-5 standard](https://github.com/neo-project/proposals/blob/master/nep-5.mediawiki).
- Therefore, every time users call methods like `.balanceOf()` or `.transfer()`, the NEP5 class will internally either call the invoke RPC method or build a `ContractInvocation` object and perform the call to the given contract. 
- The contract address/scripthash  should be mandatory in order to construct the NEP5 class and start interacting with the contract

**Comment by Priyanshu-soni** [comment]
NEP3j lib is now updated for NEP-5 token contracts API, so we can now use The wrapper class "NEP5"  with same methods as described in the NEP-5 standard
