### ISSUE TITLE
Support a function to deserialize a transaction hex string.

### ISSUE THREAD

**Issue by chenquanyu** [neow3j/neow3j#76]
Like code below:
```
        byte[] tx = Numeric.hexStringToByteArray(signedTransaction);
        TransactionType transactionType = TransactionType.valueOf(tx[0]);

        RawTransaction rawTransaction = null;

        if (transactionType == TransactionType.CONTRACT_TRANSACTION) {
            rawTransaction = NeoSerializableInterface.from(tx, ContractTransaction.class);
        } else if (transactionType == TransactionType.CLAIM_TRANSACTION) {
            rawTransaction = NeoSerializableInterface.from(tx, ClaimTransaction.class);
        } else {
            rawTransaction = NeoSerializableInterface.from(tx, InvocationTransaction.class);
        }


```

**Comment by claudemiller** [comment]
I added a `fromArray()` method directly on the RawTransaction without any inheritance from `NeoSerializable` or ``NeoSerializableInterface`. We could add this static method to the abstract `NeoSerializable` so that all implementing classes have it. Problem is that then every implementing class has to override to actually deserialize with its own type. This can't be done in the static context in the abstract base class. Or at least a static `getClass()` method would have to be added to the `NeoSerializable` subclasses, which `NeoSerializable` can then call in the static `fromArray()` method to instantiate the correct object.

In any case the problem is that `RawTransaction` and the implementing transaction types are not in the same project module. I had to move the RawTransaction and all its subparts to the core module. Semantically it makes sense that it is not in crypto anymore. But now we have a breaking change which requires a new major neow3j version if we strictly follow semantic versioning.

We have to decide if we nevertheless want to include these changes into a minor version or if we want to wait with the feature until we release the next major version (3.0.0).

**Comment by claudemiller** [comment]
Waiting for release 3.0.0

**Comment by csmuller** [comment]
Because of our focus on Neo 3, we will not release another major version of neow3j for Neo 2. Therefore the above changes will most probable not make it into Neo 2 anymore because they are breaking changes.

In Neo 3 this issue doesn't apply because the transaction model has changed to one single transaction type.
