### ISSUE TITLE
Transform notifications state address to Neo N3 address

### ISSUE THREAD

**Issue by bobbyatond** [neow3j/neow3j#777]
halo, I would like to know , there is a method to transform address from application notifications status to Neo3 address format or not?

**Comment by mialbu** [comment]
Hey @bobbyatond

You can use `getAddress` from the `StackItem` that holds the address data.
Note, that the notification state probably is a stack item of type Array. So, you first have to use `getList` and get the stack item with the address data at the according index.

```java
StackItem notificationState = notification.getState();
List<StackItem> stateValues = notificationState.getList();
StackItem addressStackItem = stateValues.get(0);
String address = addressStackItem.getAddress();
```

or in a one-liner:

```java
String address = notification.getState().getList().get(0).getAddress();
```

<img width="784" alt="image" src="https://user-images.githubusercontent.com/53603111/168251385-6ebeca05-9ab3-46d0-817d-010fd066118a.png">

Does that answer your question?

**Comment by mialbu** [comment]
@bobbyatond 
The Base64 string you used (`zLu8QtI7WjEO63J/DBH0h+SJjOg=`) represents the little-endian format of the script hash. In neow3j, script hashes (i.e., `Hash160`) are always handled in big-endian. That's why the bytes are reversed in the process before a `Hash160` object is instantiated from it.

You can achieve the same you did with the code below, without manually implementing the concatenation with the checksum and the address version.

```java
new Hash160(ArrayUtils.reverseArray(Base64.decode("zLu8QtI7WjEO63J/DBH0h+SJjOg="))).toAddress()
```

**Comment by mialbu** [comment]
I assume your question was answered. Otherwise, don't hesitate to reopen the issue again. :+1:

**Comment by bobbyatond** [comment]
thanks
