### ISSUE TITLE
Evaluate support for String concatenation with different types

### ISSUE THREAD

**Issue by mialbu** [neow3j/neow3j#780]
Evaluate whether it is possible to support concatenation of Strings with other types (e.g., long, byte, short, ...) in the compiler.

In String concatenations, neow3j enforces all types to be Strings because the concatenation with a non-final integer value leads to the integer being transformed as ASCII decimal value.

*For example:*

In the example code below, the method `concat()` would not return "token#48", but "token#0". This is because the decimal value 48 maps to the char `0` in the ASCII table. The dev needs to use e.g., `StdLib.itao(getInt())` to achieve "token#48".

```java
public static int getInt() {
    return 48;
}

public static String concat() {
    return "token#" + getInt();
}
```

This relates to #760 and #779.

**Comment by csmuller** [comment]
I'm in favor of closing this, since we specifically implemented exceptions for devs that try to concatenate strings with non-string types. Of course, it would be nice to support string concatenation with numeral types, but I don't think it's important now. There are other ways to do it, e.g., `StdLib.itoa(...)`.
