### ISSUE TITLE
The invoke() function in ContractInvocation can return Boolean

### ISSUE THREAD

**Issue by chenquanyu** [neow3j/neow3j#81]
The invoke() function in ContractInvocation can return Boolean to tell whether the transaction passes the local verification.

**Comment by claudemiller** [comment]
@chenquanyu If the transaction does not pass verification on the node, then the error is set in the response object. At the moment the `invoke()` function throws an `ErrorResponseException` in that case.  
If we change the return type to boolean it will always return true because if it is false the exception is thrown first.

If we don't throw the `ErrorResponseException` and return false instead, the developer cannot access the error message of the response. 

We could return the `NeoSendRawTransaction` object. With that, the developer can check for the error himself. But I don't think that this has benefits in comparison to the current approach (i.e. throwing the exception with the error in it).

What do you think?

**Comment by claudemiller** [comment]
@chenquanyu If you don't have any objections, I will close this issue.
