### ISSUE TITLE
The rawResponse field is null after RPC call.

### ISSUE THREAD

**Issue by chenquanyu** [neow3j/neow3j#82]
![image](https://user-images.githubusercontent.com/4393234/62342231-b7436280-b518-11e9-9e76-0d22d9a12da5.png)

**Comment by gsmachado** [comment]
This is not a bug. Just needs clarification on how to use the library.

If you would like to get the `rawResponse` in every response, you simply need to instantiate the `HttpService` class with the `includeRawResponse` attribute (`boolean`) indicating that.

Thus, in this example, you will get the raw response:

```java
    public static void main(String[] args) throws IOException {
        Neow3j neow3j = Neow3j.build(new HttpService("http://localhost:30333", true));
        
        NeoGetAccountState accountState = neow3j.getAccountState("AK2nJJpJr6o664CWJKi1QRXjqeic2zRp8y")
                .send();
        
        System.out.println(accountState.getRawResponse());
    }
```

We don't set the raw response in every single response by default since this feature could demand a considerable amount of memory usage. Then, it's always better to give the freedom to developers on setting such flag or not. 

I will add JavaDoc documentation to the method in order to make it more clear.

**Comment by chenquanyu** [comment]
Thanks👍
